### ISSUE TITLE
Passwords containing ; are truncated in process call to walletd

### ISSUE THREAD

**Issue by BagJo** [turtlecoin/desktop-xamarin#14]
I used a password containing a semicolon in the middle. The wallet was created and syncing, everthings fine.
When i wanted to reopen or backup private keys, the wallet wouldn't let be because of a wrong password.

I found out about the Process.Start()-Call to walletd and the specified password in the arguments. I took a look at the running process and noticed, that the password in the command-line was truncated before the semicolon. Using the truncated password worked just fine.

I think this should be fixed as it makes it very hard to use randomly generated strong passwords on that wallet.

**Comment by SolarstormTM** [comment]
This might be my problem too. https://github.com/turtlecoin/desktop-xamarin/issues/10#issuecomment-366261773

**Comment by codingwithredbull** [comment]
I turns out that these password issues are from a non escaped password entry on a stdin for walletd. Basically at special characters picked up by cmd will result in the password stopping at said special character. 

The good news is, if you have funds in these wallets, you have your password, it is simply truncated to the position of the first invalid special character.

A push has already been sent to fix this, and I'm simply waiting on a additional approval to merge. 

Another issues I would like to address in the same comment is the RPC TIMEOUT errors many get. Sadly this is because walletd code has changed and the Blockchain is now bigger. This is causing the daemon to take a extraordinary amount of time importing and verifying blocks while it was away. This causes the GUI to believe the rpc is not responding, however if you look in walletd.log you will see the import sync messages. If you suffer from this annoying bug, allow the RPC error message box to remain up with out clicking "ok". Periodically check the walletd.log and look for the syncing to complete. When this occurs, simply restart the wallet GUI and ur good. This of course is a work around until such a time that I can fix this properly.

**Comment by codingwithredbull** [comment]
should be resolved with version 1.0.6625.36022. Please use the latest version, and reopen the ticket if the issue persists. Thanks!

Thank you to @NoshCoin for the password command line push also
