### ISSUE TITLE
Restored view public key doesn't correspond to secret key

### ISSUE THREAD

**Issue by Keyoutofsync** [turtlecoin/desktop-xamarin#17]
Hello all,

I have been having issue with opening the wallet again. In the log file, I see "Restored view public key doesn't correspond to secret key". Any help would be appreciated!

**Comment by ZedPea** [comment]
This means your password is wrong. If you're sure it's correct, then it could be due to some of the reported issues with passwords not being stored correctly, check a few of the other threads.

**Comment by mns-33** [comment]
Thanks ZedPea. I am certain that the password is correct. I did not change anything. Just turned off the wallet and restarted.

**Comment by ZedPea** [comment]
These threads might be informative - https://github.com/turtlecoin/desktop-xamarin/issues/14
https://github.com/turtlecoin/desktop-xamarin/issues/10

**Comment by codingwithredbull** [comment]
I turns out that these password issues are from a non escaped password entry on a stdin for walletd. Basically at special characters picked up by cmd will result in the password stopping at said special character. 

The good news is, if you have funds in these wallets, you have your password, it is simply truncated to the position of the first invalid special character.

A push has already been sent to fix this, and I'm simply waiting on a additional approval to merge. 

Another issues I would like to address in the same comment is the RPC TIMEOUT errors many get. Sadly this is because walletd code has changed and the Blockchain is now bigger. This is causing the daemon to take a extraordinary amount of time importing and verifying blocks while it was away. This causes the GUI to believe the rpc is not responding, however if you look in walletd.log you will see the import sync messages. If you suffer from this annoying bug, allow the RPC error message box to remain up with out clicking "ok". Periodically check the walletd.log and look for the syncing to complete. When this occurs, simply restart the wallet GUI and ur good. This of course is a work around until such a time that I can fix this properly.

**Comment by mns-33** [comment]
It is working again. I had to go back to a release that was 25 days ago. I still do not see all the balance but I do not have the "Restored view public Key issue" anymore.

**Comment by codingwithredbull** [comment]
Thanks for tuor reporting, it helps and it's also rather weird a older release would matter. 

However I need to stress to you that anything before daemon 3.0 is VULNERABLE to a exploit attack and suggest not running it at all. 

Please perform the actions you need in this wallet with the working version, and remove the older version. I will remove these from GitHub.

The alternative would be to also wait for the. New version that will fix this issue.

**Comment by Keyoutofsync** [comment]
I see. Thank you codingwithredbull. I will not run the wallet for now til the issue is fixed.

**Comment by codingwithredbull** [comment]
should be resolved with version 1.0.6625.36022. Please use the latest version, and reopen the ticket if the issue persists. Thanks!

**Comment by Keyoutofsync** [comment]
It works now! Thanks! Appreciate the quick turn around.

I tried out the key export feature and it did say that the password incorrect. I am not sure if that would be fixed with other reported items for password.
