### ISSUE TITLE
Daemon Connection failed unable to keep daemon up

### ISSUE THREAD

**Issue by sp33dy** [turtlecoin/desktop-xamarin#25]
Hi,

Version updated to 1.0.6625.36022 and I get the above message. This is also flagged up by a few others in the Reddit.

https://www.reddit.com/r/TRTL/comments/80sgt6/daemon_connection_failed_unable_to_keep_daemon_up/

Something for us to worry about? Or is this likely to be some configuration issue on our Windows machines?

Thanks and kind regards

**Comment by ereptor81** [comment]
Most of the time this is due to the walletd process still being open from a previous instance of the wallet. Close the wallet, check taskmanager for walletd and end it if it's running, and then try reopening the wallet. If that doesn't work, check the wallet folder for a walletd.log and it should shed more light on the error you are having. 

Drop by #help in discord and someone can help get you up and running.

**Comment by sp33dy** [comment]
I'd checked for all processes before posting the error and found none. I've just rebooted and ensured no other wallet, of any other coin, is in operation but still get the same issue.

Just seen your last point about the log. There's a report of the corrupted blockchain in there. Let me go empty it out and let it resynch again. Fingers crossed, and thanks.

**Comment by ereptor81** [comment]
Bootstrap will have you up and running more quickly with the corrupted chain: https://github.com/turtlecoin/turtlecoin/wiki/Bootstrapping-the-Blockchain

**Comment by sp33dy** [comment]
Ah brill, thanks!

**Comment by sp33dy** [comment]
You can close this as resolved; I believe. :)
